# Generated by Django 5.0.6 on 2024-06-18 16:39

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=100)),
                ("phone", models.CharField(max_length=15)),
                ("birthday", models.DateField()),
                ("website", models.URLField()),
                ("city", models.CharField(max_length=100)),
                ("age", models.IntegerField()),
                ("degree", models.CharField(max_length=100)),
                (
                    "freelance",
                    models.CharField(
                        choices=[
                            ("Available", "Available"),
                            ("Not Available", "Not Available"),
                        ],
                        max_length=20,
                    ),
                ),
                ("picture", models.ImageField(upload_to="profile_picture")),
                ("heading1", models.CharField(max_length=50)),
                ("heading2", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=300)),
            ],
        ),
    ]
