# Generated by Django 5.0.6 on 2024-06-18 17:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("adminapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("degree", models.CharField(max_length=200)),
                ("start_year", models.CharField(max_length=4)),
                ("end_year", models.CharField(max_length=4)),
                ("institution", models.CharField(max_length=200)),
                ("location", models.CharField(max_length=200)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="ProfessionalExperience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("start_year", models.CharField(max_length=4)),
                ("end_year", models.CharField(max_length=4)),
                ("company", models.CharField(max_length=200)),
                ("location", models.CharField(max_length=200)),
                ("description", models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name="userdetails",
            name="description",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="userdetails",
            name="heading1",
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name="userdetails",
            name="heading2",
            field=models.CharField(max_length=150),
        ),
    ]
