# Generated by Django 5.0.6 on 2024-06-19 03:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("adminapp", "0002_education_professionalexperience_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Projects",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("project_picture", models.ImageField(upload_to="project_pictures")),
                ("project_category", models.CharField(max_length=200)),
                ("project_description", models.TextField()),
                ("client_name", models.CharField(max_length=200)),
                ("client_note", models.CharField(max_length=200)),
                ("project_date", models.DateField()),
            ],
        ),
    ]
