# Generated by Django 5.0.6 on 2024-06-19 03:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("adminapp", "0003_projects"),
    ]

    operations = [
        migrations.CreateModel(
            name="Services",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
            ],
        ),
    ]
